// generated by IDE, do not edit it.
package com.ccand99.apt

import com.autel.drone.sdk.vmodelx.manager.keyvalue.key.AutelActionKeyInfo
import java.lang.Void

public object WaypointMissionKey {
    public val component: ComponentType = ComponentType.MISSION

    public val keyEnter: AutelActionKeyInfo<Void, Void> = AutelActionKeyInfo(
        component.value,
        MessageTypeConstant.MISSION_WAYPOINT_ENTER_MSG,
        AutelEmptyConvert(),
        AutelEmptyConvert()
    ).canGet(true).canSet(true)

    public val keyExit: AutelActionKeyInfo<Void, MissionWaypointStatusReportNtfyBean> =
        AutelActionKeyInfo(
            component.value,
            MessageTypeConstant.MISSION_WAYPOINT_ENTER_MSG,
            AutelEmptyConvert(),
            AutelEmptyConvert()
        ).canGet(true).canPerformAction(true)
}